"""early access submissions

Revision ID: 004_early_access_submissions
Revises: 003_result_rows_and_actions
Create Date: 2026-09-25 14:25:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004_early_access_submissions'
down_revision = '003'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_access_submissions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('role', sa.String(length=100), nullable=True),
        sa.Column('selected_features', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('idea', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_access_submissions_email'), 'early_access_submissions', ['email'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_early_access_submissions_email'), table_name='early_access_submissions')
    op.drop_table('early_access_submissions')
    # ### end Alembic commands ###
